export const datas = 
[
  {
    "key" : 0,
    "ticket_number": 8666497,
    "customer_name": "MARZUKI, SH",
    "date_create": "18/10/2024 15:43",
    "date_response": "18/10/2024 16:17",
    "account_number": 1000957524,
    "problem_subject": "Internet & IPTV ( LOS )",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. QUANTUM - IKR",
    "kota": "Kota Medan",
    "kelurahan": "Tanjung Sari",
    "argo_start": "19/10/2024 08:00",
    "ip_address": "0.0.0.0",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": ""
  },
  {
    "key" : 1,
    "ticket_number": 8666380,
    "customer_name": "Syamsul Bahri Chan",
    "date_create": "18/10/2024 15:15",
    "date_response": "18/10/2024 16:17",
    "account_number": 1000898839,
    "problem_subject": "Internet & IPTV ( LOS )",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. QUANTUM - IKR",
    "kota": "Kota Medan",
    "kelurahan": "Sei Sikambing B",
    "argo_start": "19/10/2024 08:00",
    "ip_address": "0.0.0.0",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Regular"
  },
  {
    "key" : 2,
    "ticket_number": 8666374,
    "customer_name": "SITI ZAINAB",
    "date_create": "18/10/2024 15:13",
    "date_response": "18/10/2024 16:08",
    "account_number": 1000840081,
    "problem_subject": "Internet & IPTV(ONT LOS [SE])",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. Lancesoft - O&M",
    "kota": "Kota Medan",
    "kelurahan": "Tanjung Rejo",
    "argo_start": "19/10/2024 08:00",
    "ip_address": "0.0.0.0",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Regular"
  },
  {
    "key" : 3,
    "ticket_number": 8666364,
    "customer_name": "EVA FAHRIZAH",
    "date_create": "18/10/2024 15:11",
    "date_response": "18/10/2024 15:52",
    "account_number": 1000596134,
    "problem_subject": "Internet & IPTV - ONT LOS [GOLD][SE][SF]",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. QUANTUM - IKR",
    "kota": "Kota Jakarta Barat",
    "kelurahan": "Kelapa Dua",
    "argo_start": "19/10/2024 08:00",
    "ip_address": "0.0.0.0",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Gold"
  },
  {
    "key" : 4,
    "ticket_number": 8666355,
    "customer_name": "DICKY YOSEPH SIREGAR. SE",
    "date_create": "18/10/2024 15:09",
    "date_response": "18/10/2024 16:03",
    "account_number": 1000584874,
    "problem_subject": "Internet[Internet Slow Redaman Rendah][SE]",
    "nature": "Complaint",
    "category": "Internet",
    "sub_category": "Internet Slow Redaman Rendah",
    "sla": "24 Jam",
    "vendor": "PT. CKK - IKR",
    "kota": "Kota Bandung",
    "kelurahan": "Ancol",
    "argo_start": "19/10/2024 08:00",
    "TX / RX": "TX : 1.98 dBm/ RX : -28.86 dBm",
    "ip_address": "10.251.14.23",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Regular"
  },
  {
    "key" : 5,
    "ticket_number": 8666351,
    "customer_name": "M SYAMSUL BAHRI",
    "date_create": "18/10/2024 15:08",
    "date_response": "18/10/2024 16:06",
    "account_number": 1000783160,
    "problem_subject": "Internet & IPTV [ONT LOS][SE] [Platinum]",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. Satu Visi - IKR",
    "kota": "Kota Jakarta Selatan",
    "kelurahan": "Pejaten Timur",
    "argo_start": "19/10/2024 08:00",
    "TX / RX": "TX : 0/ RX : 0",
    "ip_address": "-",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Platinum"
  },
  {
    "key" : 6,
    "ticket_number": 8666349,
    "customer_name": "LILI HASTUTI",
    "date_create": "18/10/2024 15:07",
    "date_response": "18/10/2024 16:07",
    "account_number": 1000233095,
    "problem_subject": "Internet & IPTV [ONT LOS][SE][Gold][REPEATED 1X]",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. CKK - IKR",
    "kota": "Kota Semarang",
    "kelurahan": "Pedurungan Kidul",
    "argo_start": "19/10/2024 08:00",
    "ip_address": "0.0.0.0",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Gold"
  },
  {
    "key" : 7,
    "ticket_number": 8666344,
    "customer_name": "ALDO APRIAN PRATAMA ST",
    "date_create": "18/10/2024 15:05",
    "date_response": "18/10/2024 15:53",
    "account_number": 1000784855,
    "problem_subject": "INTERNET & IPTV [ONT LOS][SE][GOLD]",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. QUANTUM - IKR",
    "kota": "Kota Surabaya",
    "kelurahan": "Dukuh Setro",
    "argo_start": "19/10/2024 08:00",
    "ip_address": "0.0.0.0",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Gold"
  },
  {
    "key" : 8,
    "ticket_number": 8666343,
    "customer_name": "HARTONO SADARMO",
    "date_create": "18/10/2024 15:05",
    "date_response": "18/10/2024 16:08",
    "account_number": 1000029448,
    "problem_subject": "INTERNET & IPTV - ONT LOS [SE]",
    "nature": "Complaint",
    "category": "Internet & IPTV",
    "sub_category": "ONT LOS",
    "sla": "24 Jam",
    "vendor": "PT. CKK - IKR",
    "kota": "Kota Semarang",
    "kelurahan": "Panggung Lor",
    "argo_start": "19/10/2024 08:00",
    "ip_address": "0.0.0.0",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Regular"
  },
  {
    "key" : 9,
    "ticket_number": 8666342,
    "customer_name": "KAMTO",
    "date_create": "18/10/2024 15:05",
    "date_response": "18/10/2024 16:08",
    "account_number": 1000695605,
    "problem_subject": "INTERNET - INTERNET SLOW REDAMAN RENDAH[SE]",
    "nature": "Complaint",
    "category": "Internet",
    "sub_category": "Internet Slow Redaman Rendah",
    "sla": "24 Jam",
    "vendor": "PT. CKK - IKR",
    "kota": "Kota Semarang",
    "kelurahan": "Tlogosari Kulon",
    "argo_start": "19/10/2024 08:00",
    "TX / RX": "TX : 2.654 dBm/ RX : -27.96 dBm",
    "ip_address": "10.249.184.81",
    "duration": "14 jam dari sekarang",
    "status": "",
    "segmentasi": "Regular"
  },

]
